### ISSUE TITLE
Tuple index out of range during processing

### ISSUE THREAD

**Issue by JJFogg** [id03/binoculars#22]
Hi,

When processing the scans using both the binoculars or the binoculars-processgui programs it gets to the end of the last scan and then throws this tuple index out of range error. I'm not exactly sure what is causing the error but when using the binoculars program it shows the following message in the terminal:

Traceback (most recent call last):
  File "binoculars", line 352, in <module>
    subcommands[sys.argv[1]](sys.argv[2:])
  File "binoculars", line 319, in command_process
    binoculars.main.Main.from_args(args)  # start of main thread
  File "/usr/local/lib/python2.7/dist-packages/binoculars/main.py", line 70, in from_args
    return cls(configobj, args.command)
  File "/usr/local/lib/python2.7/dist-packages/binoculars/main.py", line 53, in __init__
    self.run(command)
  File "/usr/local/lib/python2.7/dist-packages/binoculars/main.py", line 89, in run
    self.dispatcher.config.destination.store(self.result)
  File "/usr/local/lib/python2.7/dist-packages/binoculars/dispatcher.py", line 48, in store
    for sp, fn in zip(verse.spaces, self.final_filenames()):
  File "/usr/local/lib/python2.7/dist-packages/binoculars/dispatcher.py", line 66, in final_filenames
    fn = self.filename.format(**self.opts)
IndexError: tuple index out of range

if you need the config file I am using or anything else to see where I am going wrong just let me know.

Thanks

**Comment by Onderwaater** [comment]
Hi. Yes the config file would help. Thanks

**Comment by JJFogg** [comment]
Here it is.
[configtest.txt](https://github.com/id03/binoculars/files/434320/configtest.txt)

**Comment by Onderwaater** [comment]
In your specification for the destination:

destination= /home/josh/Documents/Data/esrfnov2015/hc2014_img/hc2014_zap01/au111_01img/Au111_01{90}--{94}.hdf5

you need to replace the indices in the curly brackets 'first' or 'last'. self.opts does not contain an index for the values of 90 and 94.
