### ISSUE TITLE
TypeError when importing example CTR space hdf5 files

### ISSUE THREAD

**Issue by P-Mousley** [id03/binoculars#27]
I am currently trying to run binoculars-gui.py (cloned from [here](https://github.com/id03/binoculars) ) python 3.4.2 from the Anaconda3 package. When trying to load example hdf5 CTR space files (cloned from [here](https://github.com/id03/BINoculars-binaries) ) using the import space option from the file menu , i receive the following error message:

Traceback (most recent call last):
  File "C:\my-www\binoculars\scripts\binoculars-gui.py", line 357, in add_to_project
    widget.addspace(str(name), True)
  File "C:\my-www\binoculars\scripts\binoculars-gui.py", line 932, in addspace
    self.table.add_space(filename, add)
  File "C:\my-www\binoculars\scripts\binoculars-gui.py", line 1045, in add_space
    item = QtGui.QTableWidgetItem(','.join(list(ax.label.lower() for ax in container.get_ax())))
TypeError: sequence item 0: expected str instance, bytes found

On attempting to get information to debug i found that for the class SpaceContainer the value of self.space is None. This means  'get_ax()' returns 'binoculars.space.Axes.fromfile(self.label)' which when printed is shown as:

Axes (3 dimensions, -560788133 points, 1.7 GB) {
    Axis b'H' (min=-68.0, max=58.0, res=0.002, count=63001)
    Axis b'K' (min=-533.0, max=-458.0, res=0.002, count=37501)
    Axis b'L' (min=7.0, max=198.0, res=0.02, count=9551)
}

the error is hit when this is passed to the add_space variable in class TableWidget in line 1045.
Has anyone come across this issue or something similar? Does anyone know a way to fix this so that it can read in the hdf5 files correctly?

**Comment by P-Mousley** [comment]
I have downgraded my python package to Python 2.7.5 from Anaconda 1.7.0, and this error is no longer present.
